language: c
script: bash -ex .travis-ci.sh
env:
  matrix:
    - DOWNSTREAM=none
    - DOWNSTREAM=verdi
sudo: false
notifications:
  slack:
    secure: AaJDFxx98pMhb4ZaA2uqZ/itjmKCu/Ig33NxHxdn3GZotzAds/cwwFWq2aEpiyfQCSn7UOiEjMYNTHaI/HUnt71CJbOMNGqGCVG/09Jh4UYxKT3Gy7MPq5ClTUQ2577bNVY46yMJ9nSoByXvG0caDMICO72amiQZfQdOiXO5IwcjjhXlv2LswQjOFSd8OPI7tkt5g5FoWHCJbbb1QjhuXoeyVKcrXgmS12kwg0w6O1kVL6uTk9NnOt6g/D6aaPGR1xi9nJHcOu4T0UPwnbzfJMR0z4lAFNz/jmHuAwiyJj7HQAGl7uFDU5oh0SwVv0JAE31Nraez8v4wrQu0vEwq+oNYjbmNoVG/G/ow9KnZier7Ti8D920R9nsCsKKVMm8rYYFVuM7Fd3OQiDpQ2Dn3+s2MAl0tqLpYV6VHsu3WxLR6+VljoPL4Mica23ehAtSVZspok0BLSVSTNTnwF+nqVE/C1kJPc35WZGcaY/sx5qCuU06WDvj8dgkOwkjVf3Ar0o8XvpEaHe1dQSjwfygo/9g0Cy6RwXitQ/ojPUOIF2CCTgGdJ7/woiuIy50/8MTsbw3P1RrT9Gh/PsTB5l2KzqgKEcAYGlvIeRqG8DfLEviYaLJjVnPw0yJ1E4mY5amKxHwbxG9TGYPrVz44fhOkx3ASwxmvGGu3Hcn9AuhdGjE=
